Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2020-12, with the labels that each got.

#771 [CAZB-3529] Content update on the Privacy policy page
  app/views/static_pages/privacy_notice.html.haml
  features/static_pages.feature
Labels: documentation

#773 [CAZB-3646] Content update on CSV upload pages
  app/views/vehicles_management/uploads/_description.html.haml
Labels: documentation

#775 [CAZB-3637] Validate number of vehicles to be uploaded
  Gemfile.lock
  app/controllers/vehicles_management/uploads_controller.rb
  app/services/vehicles_management/count_vehicles.rb
  app/services/vehicles_management/upload_file.rb
  config/application.rb
  config/locales/en.yml
  features/step_definitions/vehicles_management/uploads_step.rb
  features/vehicles_management/uploads.feature
  package.json
  spec/api_wrappers/account_details/account_details_spec.rb
  spec/api_wrappers/accounts_api/accounts/account_spec.rb
  spec/api_wrappers/accounts_api/accounts/create_account_spec.rb
  spec/api_wrappers/accounts_api/accounts/csv_exports_spec.rb
  spec/api_wrappers/accounts_api/auth/sign_in_spec.rb
  spec/api_wrappers/accounts_api/users/create_user_spec.rb
  spec/api_wrappers/accounts_api/users/resend_verification_spec.rb
  spec/api_wrappers/accounts_api/users/user_spec.rb
  spec/api_wrappers/accounts_api/users/users_spec.rb
  spec/api_wrappers/compliance_checker_api/clean_air_zones_spec.rb
  spec/api_wrappers/compliance_checker_api/vehicle_details_spec.rb
  spec/api_wrappers/debits_api/create_mandate_spec.rb
  spec/api_wrappers/debits_api/create_payment_spec.rb
  spec/api_wrappers/payment_history_api/payment_details_spec.rb
  spec/api_wrappers/payments_api/create_payment_spec.rb
  spec/api_wrappers/payments_api/payment_status_spec.rb
  spec/models/direct_debits/debit_spec.rb
  spec/models/manage_vehicles/chargeable_fleet_spec.rb
  spec/models/manage_vehicles/fleet_spec.rb
  spec/requests/vehicles_management/uploads/create_spec.rb
  spec/services/vehicles_management/count_vehicles_spec.rb
  spec/services/vehicles_management/large_fleet_threshold_spec.rb
  spec/services/vehicles_management/upload_file_spec.rb
  yarn.lock
Labels: documentation

#776 [CAZB-3505] Allow html content to job errors
  app/views/vehicles_management/uploads/_job_errors.html.haml
Labels: enhancement

#777 [CAZB-3637] Validate number of vehicles to be uploaded
  app/services/vehicles_management/upload_file.rb
Labels: bug

#778 [CAZB-3632] Content update on Privacy Notice page
  app/views/static_pages/privacy_notice.html.haml
  features/static_pages.feature
Labels: documentation

#779 [CAZB-3648] Search feature on the Manage vehicles page
  app/api_wrappers/fleets_api.rb
  app/controllers/concerns/caz_lock.rb
  app/controllers/vehicles_management/fleets_controller.rb
  app/controllers/vehicles_management/vehicles_controller.rb
  app/forms/vehicles_management/search_vrn_form.rb
  app/forms/vrn_form.rb
  app/models/vehicles_management/fleet.rb
  app/views/vehicles_management/fleets/_search.html.haml
  app/views/vehicles_management/fleets/index.html.haml
  app/views/vehicles_management/fleets/vrn_not_found.html.haml
  config/routes.rb
  spec/forms/vehicles_management/search_vrn_form_spec.rb
  spec/forms/vrn_form_spec.rb
  spec/models/manage_vehicles/fleet_spec.rb
  spec/requests/payments/payments/submit_search_spec.rb
  spec/requests/payments/payments/vrn_not_found_spec.rb
  spec/requests/vehicles_management/fleets/index_spec.rb
  spec/requests/vehicles_management/fleets/submit_search_spec.rb
  spec/requests/vehicles_management/fleets/vrn_not_found_spec.rb
  spec/support/fleet_factory.rb
Labels: documentation

#780 [CAZB-3648] Fix pagination when using vrn search
  app/views/vehicles_management/fleets/_pagination_button.html.haml
Labels: documentation

#802 [CAZB-3773] Hide manage vehicles search input
  app/views/vehicles_management/fleets/index.html.haml
Labels: bug

#804 [CAZB-3768] Copy change when reached max of 10 users
  app/views/users_management/users/index.html.haml
  features/users_management/manage_users.feature
Labels: documentation

#807 Promote Accounts v1.6.2 to Staging
  .drone2.yml
  app/controllers/static_pages_controller.rb
  app/views/layouts/_footer.html.haml
  app/views/layouts/disabled_links/_footer.html.haml
  app/views/organisations/organisations/new.html.haml
  app/views/static_pages/terms_and_conditions.html.haml
  app/views/users_management/users/index.html.haml
  app/views/vehicles_management/fleets/index.html.haml
  config/routes.rb
  features/organisations.feature
  features/static_pages.feature
  features/users_management/manage_users.feature
  spec/requests/static_pages_spec.rb
Labels: Accounts v1.6.2, dont merge yet, release

#813 [CAZB-3579] Update wording for button on the matrix page
  app/controllers/payments/payments_controller.rb
  app/views/payments/payments/matrix.html.haml
  features/debits.feature
  features/payments.feature
  features/step_definitions/helper_steps.rb
  spec/requests/payments/payments/submit_spec.rb
Labels: documentation

#815 [CAZB-3718] Change urls
  .rubocop.yml
  Gemfile.lock
  app/controllers/dashboard_controller.rb
  app/controllers/direct_debits/debits_controller.rb
  app/controllers/organisations/organisations_controller.rb
  app/controllers/payments/credit_cards_controller.rb
  app/controllers/payments/payments_controller.rb
  app/controllers/vehicles_management/fleets_controller.rb
  app/forms/vehicles_management/submission_method_form.rb
  app/views/devise/sessions/new.html.haml
  app/views/direct_debits/debits/cancel.html.haml
  app/views/direct_debits/debits/index.html.haml
  app/views/direct_debits/debits/set_up.html.haml
  app/views/direct_debits/debits/unsuccessful.html.haml
  app/views/layouts/_navbar.haml
  app/views/layouts/disabled_links/_navbar.haml
  app/views/organisations/organisations/cannot_create.html.haml
  app/views/organisations/organisations/create_account.html.haml
  app/views/organisations/organisations/email_sent.html.haml
  app/views/organisations/organisations/how_many_vehicles.html.haml
  app/views/organisations/organisations/sign_in_details.html.haml
  app/views/organisations/organisations/verification_expired.html.haml
  app/views/payments/payments/unsuccessful.html.haml
  app/views/vehicles_management/fleets/choose_method.html.haml
  app/views/vehicles_management/fleets/first_upload.html.haml
  app/views/vehicles_management/fleets/index.html.haml
  app/views/vehicles_management/fleets/remove.html.haml
  app/views/vehicles_management/uploads/index.html.haml
  config/routes.rb
  features/debits.feature
  features/step_definitions/debits_steps.rb
  features/step_definitions/organisations_steps.rb
  features/step_definitions/vehicles_management/fleets_steps.rb
  package.json
  spec/api_wrappers/debits_api/create_mandate_spec.rb
  spec/fixtures/responses/debits/create_mandate.json
  spec/forms/vehicles_management/submission_method_form_spec.rb
  spec/requests/direct_debits/debits/index_spec.rb
  spec/requests/direct_debits/debits/initiate_spec.rb
  spec/requests/direct_debits/debits/set_up_spec.rb
  spec/requests/direct_debits/debits/submit_set_up_spec.rb
  spec/requests/direct_debits/debits/unsuccessful_spec.rb
  spec/requests/organisations/create_account_spec.rb
  spec/requests/organisations/fleet_check_spec.rb
  spec/requests/organisations/sign_in_details_spec.rb
  spec/requests/organisations/submit_create_account_spec.rb
  spec/requests/organisations/submit_fleet_check_spec.rb
  spec/requests/organisations/submit_sign_in_details_spec.rb
  spec/requests/payments/payments/index_spec.rb
  spec/requests/payments/payments/unsuccessful_spec.rb
  spec/requests/vehicles_management/fleets/assign_remove_spec.rb
  spec/requests/vehicles_management/fleets/confirm_remove_spec.rb
  spec/requests/vehicles_management/fleets/index_spec.rb
  spec/requests/vehicles_management/fleets/remove_spec.rb
  spec/requests/vehicles_management/fleets/submission_method_spec.rb
  spec/requests/vehicles_management/fleets/submit_method_spec.rb
  yarn.lock
Labels: documentation

#816 [CAZB-3726] Update page title
  app/views/layouts/application.html.haml
  app/views/vehicles_management/fleets/remove.html.haml
  app/views/vehicles_management/vehicles/not_found.html.haml
Labels: documentation

#818 [CAZB-3755] Uncomment search button
  app/views/vehicles_management/fleets/index.html.haml
Labels: bug
