Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2020-04, with the labels that each got.

#181 Remove mocks from direct debit flow
  app/api_wrappers/debits_api.rb
  app/api_wrappers/debits_api_responses.rb
  app/controllers/credit_cards_controller.rb
  app/controllers/debits_controller.rb
  app/models/direct_debit.rb
  app/models/direct_debit_details.rb
  app/models/mandate.rb
  app/services/base_payment.rb
  app/services/make_card_payment.rb
  app/services/make_debit_payment.rb
  app/views/debits/confirm.html.haml
  app/views/debits/success.html.haml
  config/routes.rb
  features/step_definitions/debits_steps.rb
  spec/api_wrappers/debits_api/caz_mandates_spec.rb
  spec/fixtures/responses/debits/active_mandates.json
  spec/fixtures/responses/debits/create_payment.json
  spec/fixtures/responses/debits/empty_mandates.json
  spec/fixtures/responses/debits/inactive_mandates.json
  spec/fixtures/responses/debits/mandates.json
  spec/models/direct_debit_details_spec.rb
  spec/models/direct_debit_spec.rb
  spec/requests/credit_cards/initiate_spec.rb
  spec/requests/debits/confirm_spec.rb
  spec/requests/debits/create_spec.rb
  spec/requests/debits/initiate_spec.rb
  spec/services/make_debit_payment_spec.rb
  spec/support/mocked_responses.rb
Labels: documentation

#182 [CAZ-2167] Allow to pay with mandate in `pending` status
  app/controllers/debits_controller.rb
  app/models/direct_debit.rb
  features/step_definitions/debits_steps.rb
  spec/requests/debits/first_mandate_spec.rb
  spec/support/mocked_responses.rb
Labels: documentation

#188 [CAZ-2268] Add compatibility between IE and babel javascript
  app/javascript/packs/payment_matrix.js
  package.json
  yarn.lock
Labels: bug

#187 [CAZ-2166] Add a return to dashboard button on the debits page
  app/views/debits/index.html.haml
Labels: bug

#186 [CAZ-2167] Add payment id to the success dd page
  app/views/debits/success.html.haml
Labels: documentation

#192 [CAZ-2303] Update the exempt page
  app/views/vehicles/exempt.html.haml
Labels: documentation

#193 [CAZ-2302] Update the not found page
  app/views/vehicles/not_found.html.haml
Labels: documentation

#194 [CAZ-2301] Update the submission method page
  app/views/fleets/submission_method.html.haml
  features/fleets.feature
  features/step_definitions/fleets_steps.rb
Labels: documentation

#195 [CAZ-2300] Update the vehicle management page
  app/views/fleets/index.html.haml
Labels: documentation

#196 [CAZ-2298] Update the upload page
  config/locales/en.yml
  features/uploads.feature
Labels: documentation

#197 [CAZ-2305] Add a return button to the Charge details page
  app/views/payments/review_details.html.haml
  features/payments.feature
Labels: documentation

#200 [CAZ-2304] Update error messaging for Clean Air Zone selection page
  config/locales/en.yml
  features/debits.feature
  features/payments.feature
Labels: documentation

#198 [CAZ-2297] Remove back link from Reset Password token expired page
  app/views/passwords/invalid.html.haml
  features/password_reset.feature
Labels: documentation

#199 [CAZ-2296] Account registration page error messaging revisions
  app/forms/email_and_password_form.rb
  spec/forms/email_and_password_form_spec.rb
Labels: documentation

#201 [CAZ-2317] Keep the company creation input data in session
  app/controllers/organisations_controller.rb
  app/views/organisations/form_input/_errored.html.haml
  app/views/organisations/form_input/_normal.html.haml
  app/views/organisations/new.html.haml
  features/organisations.feature
  features/step_definitions/helper_steps.rb
  spec/requests/organisations_controller/create_spec.rb
  spec/requests/organisations_controller/email_sent_spec.rb
  spec/requests/organisations_controller/new_credentials_spec.rb
  spec/requests/organisations_controller/resend_email_spec.rb
Labels: documentation

#207 [CAZ-2149] Validate two `at sign` symbols for email address
  app/forms/base_form.rb
  spec/models/reset_password_form_spec.rb
Labels: bug

#202 [CAZ-2317] Back button returns to the previous page state
  app/controllers/dashboard_controller.rb
  app/controllers/debits_controller.rb
  app/controllers/fleets_controller.rb
  app/controllers/organisations_controller.rb
  app/controllers/payments_controller.rb
  app/controllers/uploads_controller.rb
  app/controllers/vehicles_controller.rb
  app/forms/confirmation_form.rb
  app/helpers/payments_helper.rb
  app/views/debits/new.html.haml
  app/views/fleets/index.html.haml
  app/views/fleets/submission_method.html.haml
  app/views/organisations/form_input/_errored.html.haml
  app/views/organisations/form_input/_normal.html.haml
  app/views/organisations/new.html.haml
  app/views/payments/cancel.html.haml
  app/views/payments/matrix.html.haml
  app/views/payments/select_payment_method.html.haml
  app/views/uploads/_upload.html.haml
  app/views/vehicles/enter_details.html.haml
  app/views/vehicles/vrn_input/_errored.haml
  app/views/vehicles/vrn_input/_normal.haml
  features/organisations.feature
  features/vehicles.feature
  spec/requests/organisations_controller/create_spec.rb
  spec/requests/organisations_controller/email_sent_spec.rb
  spec/requests/organisations_controller/new_credentials_spec.rb
  spec/requests/organisations_controller/resend_email_spec.rb
  spec/requests/payments/cancel_spec.rb
Labels: documentation

#208 [NT] Redis can't read session key as a symbol
  app/controllers/organisations_controller.rb
Labels: bug

#206 Add drone configuration for UAT environment
  .drone.yml
Labels: enhancement

#209 [CAZ-2317] Stringify all cookies keys for organisation creation flow
  app/controllers/organisations_controller.rb
  app/views/organisations/form_input/_errored.html.haml
  app/views/organisations/form_input/_normal.html.haml
  app/views/organisations/new.html.haml
Labels: documentation

#205 [NT] Fix aria-label typo
  app/helpers/application_helper.rb
Labels: bug

#213 [CAZ-2294] Remove red lines for email/password fields
  lib/devise/strategies/remote.rb
Labels: documentation

#214 [CAZ-2303] Update the exempt page
  app/views/vehicles/exempt.html.haml
Labels: documentation

#216 [CAZ-2242] Bump Control Cookies to version 9
  app/javascript/styles/cookie_control.scss
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/application.html.haml
Labels: documentation

#229 [CAZ-2317] Save the previous state of submission_method page
  .rubocop.yml
  Gemfile.lock
  app/controllers/uploads_controller.rb
  app/controllers/vehicles_controller.rb
  spec/requests/uploads/download_template_spec.rb
Labels: bug

#242 [CAZ-2532] Update title on the `Review payment` page
  Gemfile.lock
  app/views/payments/review.html.haml
  features/payments.feature
  features/step_definitions/payments_steps.rb
Labels: documentation

#247 [CAZ-2581] Prevent Direct Debit dashboard feature from being hidden
  app/views/dashboard/index.html.haml
  features/dashboard.feature
Labels: documentation

#245 [CAZ-2536] Capitalise every instance of Direct Debit text
  app/api_wrappers/debits_api.rb
  app/controllers/debits_controller.rb
  app/services/make_debit_payment.rb
  app/views/dashboard/_direct_debit.html.haml
  app/views/debits/first_mandate.html.haml
  app/views/debits/index.html.haml
  app/views/debits/new.html.haml
  features/debits.feature
  features/step_definitions/debits_steps.rb
  spec/requests/debits/new_spec.rb
  spec/requests/payments/select_payment_method_spec.rb
Labels: documentation

#248 Fix dashboard feature test
  features/dashboard.feature
Labels: bug

#253 [CAZ-2533] Show choice to pay via Direct Debit if user set one up
  .drone.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/debits_controller.rb
  app/controllers/payments_controller.rb
  features/debits.feature
  features/payments.feature
  features/step_definitions/debits_steps.rb
  features/step_definitions/payments_steps.rb
  package.json
  spec/requests/payments/confirm_payment_method_spec.rb
  spec/requests/payments/select_payment_method_spec.rb
  yarn.lock
Labels: documentation

#254 [CAZ-2534] Update dashboard page
  Dockerfile.build
  Dockerfile.test
  Gemfile.lock
  app/views/dashboard/_direct_debit.html.haml
  app/views/dashboard/_make_payment.html.haml
  app/views/dashboard/_manage_vehicles.html.haml
  app/views/dashboard/index.html.haml
  features/dashboard.feature
Labels: documentation

#257 [CAZ-2616] Show Mandate ID and Creation date on payment confirm page
  app/controllers/debits_controller.rb
  app/helpers/application_helper.rb
  app/views/debits/confirm.html.haml
  spec/fixtures/responses/debits/active_mandates.json
  spec/fixtures/responses/debits/caz_mandates.json
  spec/fixtures/responses/debits/inactive_caz_mandates.json
  spec/fixtures/responses/debits/inactive_mandates.json
  spec/fixtures/responses/debits/mandates.json
Labels: documentation

#258 [CAZ-2533] Check active caz mandates on select payment method page
  app/controllers/payments_controller.rb
  features/step_definitions/fleets_steps.rb
  features/step_definitions/payments_steps.rb
  spec/requests/payments/select_payment_method_spec.rb
Labels: documentation
