Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2020-03, with the labels that each got.

#106 [CAZ-2055] Drone changes for Fleets UI prod environment
  .drone.yml
Labels: don't merge

#117 [CAZB-642] Update cookie control content and cookie page
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/static_pages_controller.rb
  app/helpers/application_helper.rb
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_footer.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/cookies/_cookie_control.html.haml
  app/views/static_pages/cookies/_ga.html.haml
  app/views/static_pages/cookies/_session.html.haml
  app/views/static_pages/cookies/_table_head.html.haml
  config/initializers/session_store.rb
  config/routes.rb
  features/static_pages.feature
  features/step_definitions/sign_in_steps.rb
  features/step_definitions/static_pages_steps.rb
  package.json
  sonar-project.properties
  spec/requests/static_pages_spec.rb
  spec/support/shared_examples/static_page.rb
  yarn.lock
Labels: documentation

#118 [NT] Fix typo on password reset page
  app/views/passwords/invalid.html.haml
Labels: bug

#121 [CAZ-2122] Hide Control Cookie buttons and add `Save and close` button
  app/views/layouts/_cookie_control.html.erb
Labels: documentation

#125 [NT] Fix Cookie Control black button
  app/javascript/packs/application.js
  app/javascript/src/cookieControl.js
Labels: bug

#120 [CAZ-2122] User password reset - wrong message for empty email
  app/forms/reset_password_form.rb
  features/password_reset.feature
  spec/forms/reset_password_form_spec.rb
Labels: bug

#128 [CAZ-2112] Remove TBA error messages and draft badges
  app/views/dashboard/user_dashboard.html.haml
  app/views/organisations/new.html.haml
  app/views/organisations/new_credentials.html.haml
  app/views/organisations/verification_failed.html.haml
  app/views/passwords/email_sent.html.haml
  app/views/passwords/index.html.haml
  app/views/passwords/invalid.html.haml
  app/views/passwords/reset.html.haml
  app/views/vehicles/details.html.haml
  config/locales/en.yml
  features/debits.feature
  features/fleets.feature
  features/organisations.feature
  features/password_reset.feature
  features/payments.feature
  features/sign_in.feature
  features/vehicles.feature
  spec/forms/confirmation_form_spec.rb
Labels: enhancement

#131 Remove require `logstash-logger` from production.rb
  config/environments/production.rb
Labels: bug

#134 [CAZ-2127] Add password hint to update password page
  app/views/dashboard/admin_dashboard.html.haml
  app/views/dashboard/user_dashboard.html.haml
  app/views/passwords/_password_input.html.haml
  app/views/passwords/index.html.haml
  features/dashboard.feature
  features/sign_in.feature
Labels: enhancement

#136 Update survey link to newly provided URL
  .drone.yml
Labels: enhancement

#135 [CAZ-2146] Add accessibility page to Fleets service
  app/controllers/static_pages_controller.rb
  app/views/layouts/_footer.html.haml
  app/views/static_pages/accessibility_statement.html.haml
  config/routes.rb
  features/static_pages.feature
  features/step_definitions/static_pages_steps.rb
  spec/requests/static_pages_spec.rb
Labels: enhancement

#137 [CAZ-2141] Update vehicle management page with latest copy
  app/helpers/application_helper.rb
  app/models/vehicle.rb
  app/views/fleets/index.html.haml
  config/application.rb
  spec/models/vehicle_spec.rb
Labels: enhancement

#133 [CAZ-2102] Dynamic content on the dashboard page
  app/controllers/dashboard_controller.rb
  app/views/dashboard/index.html.haml
  app/views/dashboard/user_dashboard.html.haml
  features/dashboard.feature
  features/organisations.feature
  features/sign_in.feature
  features/step_definitions/dashboard_steps.rb
  features/step_definitions/debits_steps.rb
  features/step_definitions/fleets_steps.rb
  features/step_definitions/helper_steps.rb
  features/step_definitions/navigate_pages_steps.rb
  features/step_definitions/sign_in_steps.rb
  features/step_definitions/uploads_step.rb
  features/step_definitions/vehicles_steps.rb
  spec/requests/dashboard_controller_spec.rb
Labels: documentation

#138 [CAZ-2149] Update email regex
  app/forms/base_form.rb
  app/views/passwords/reset.html.haml
  spec/models/reset_password_form_spec.rb
Labels: bug

#139 Minor copy update on vehicle management
  app/views/fleets/index.html.haml
Labels: enhancement

#140 [CAZ-2150] Fix duplicate error message on account registration
  app/forms/email_and_password_form.rb
  features/organisations.feature
  features/password_reset.feature
  features/step_definitions/password_reset_steps.rb
Labels: bug

#145 Update new.html.haml
  app/views/organisations/new.html.haml
Labels: bug

#143 [CAZ-2139] Dynamic content on the matrix page
  app/models/chargeable_fleet.rb
  app/views/payments/matrix/_next_week_tab.html.haml
  app/views/payments/matrix/_past_week_tab.html.haml
  features/payments.feature
  features/step_definitions/fleets_steps.rb
  features/step_definitions/payments_steps.rb
  features/support/mock_fleet.rb
  spec/fixtures/responses/chargeable_vehicles_with_unpaid_dates.json
  spec/models/chargeable_fleet_spec.rb
Labels: documentation

#148 Drone file corrections
  .drone.yml
Labels: bug

#153 [CAZ-2156] Alter text on validating submission page
  app/views/uploads/processing.html.haml
Labels: enhancement

#157 Minor CSS formatting on manage vehicles page
  app/javascript/styles/application.scss
  app/views/fleets/index.html.haml
Labels: enhancement

#158 CSS and accessibility update
  app/javascript/styles/application.scss
  app/views/fleets/index.html.haml
Labels: enhancement

#160 [CAZ-2153] Small typo correction
  app/views/payments/success.html.haml
Labels: bug

#161 [CAZ-2016] Case sensitivity fix for search
  app/api_wrappers/payments_api.rb
  app/javascript/src/payment_matrix/createHiddenInput.js
  app/views/payments/matrix/_no_chnargeable_vehicles.html.haml
Labels: bug

#164 Update view presentation logic based on PO feedback
  .drone.yml
  app/views/fleets/submission_method.html.haml
  app/views/payments/matrix.html.haml
  app/views/payments/matrix/_headling.html.haml
  app/views/payments/matrix/_no_chnargeable_vehicles.html.haml
  app/views/payments/matrix/_search.html.haml
Labels: enhancement

#165 Update references to registration number
  app/views/payments/_payment_details.html.haml
  app/views/payments/matrix/_table.html.haml
  app/views/vehicles/enter_details.html.haml
  config/locales/en.yml
  features/vehicles.feature
Labels: enhancement

#166 Wrap clear search link javascript in null check
  app/javascript/src/payment_matrix/initSearch.js
Labels: bug

#169 Update copy after PO review
  app/views/dashboard/_manage_vehicles.html.haml
  app/views/uploads/_description.html.haml
  app/views/uploads/_reupload.html.haml
  app/views/uploads/_upload.html.haml
  features/uploads.feature
  public/template.csv
Labels: enhancement

#170 Remove all whitespace from search input value
  app/javascript/src/payment_matrix/createHiddenInput.js
Labels: bug

#172 [CAZ-2010] Fixes disabled Continue button
  app/helpers/payments_helper.rb
  app/javascript/src/payment_matrix/emptyMatrixContinuePrevention.js
  app/views/payments/matrix.html.haml
Labels: bug

#173 Minor copy update
  app/views/fleets/delete.html.haml
Labels: enhancement

#177 [CAZ-2167] Add pages for direct debit flow
  app/api_wrappers/debits_api.rb
  app/controllers/application_controller.rb
  app/controllers/credit_cards_controller.rb
  app/controllers/debits_controller.rb
  app/controllers/payments_controller.rb
  app/helpers/application_helper.rb
  app/javascript/styles/application.scss
  app/javascript/styles/payment_summary.scss
  app/models/direct_debit.rb
  app/models/direct_debit_details.rb
  app/models/mandate.rb
  app/models/user.rb
  app/services/base_payment.rb
  app/services/make_card_payment.rb
  app/services/make_debit_payment.rb
  app/views/dashboard/_direct_debit.html.haml
  app/views/dashboard/index.html.haml
  app/views/debits/confirm.html.haml
  app/views/debits/first_mandate.html.haml
  app/views/debits/index.html.haml
  app/views/debits/new.html.haml
  app/views/payments/cancel_payment.html.haml
  app/views/payments/index.html.haml
  app/views/payments/review.html.haml
  app/views/payments/select_payment_method.html.haml
  config/routes.rb
  features/debits.feature
  features/payments.feature
  features/step_definitions/debits_steps.rb
  features/step_definitions/helper_steps.rb
  features/step_definitions/payments_steps.rb
  features/support/mock_debit.rb
  spec/fixtures/responses/debits/active_mandates.json
  spec/fixtures/responses/debits/add_mandate.json
  spec/fixtures/responses/debits/caz_mandates.json
  spec/fixtures/responses/debits/create_payment.json
  spec/fixtures/responses/debits/empty_mandates.json
  spec/fixtures/responses/debits/inactive_caz_mandates.json
  spec/fixtures/responses/debits/inactive_mandates.json
  spec/fixtures/responses/debits/mandates.json
  spec/fixtures/responses/mandates.json
  spec/fixtures/responses/no_account_mandates.json
  spec/models/direct_debit_spec.rb
  spec/models/mandate_spec.rb
  spec/rails_helper.rb
  spec/requests/debits/create_spec.rb
  spec/requests/debits/index_spec.rb
  spec/requests/debits/new_spec.rb
  spec/requests/payments/select_payment_method_spec.rb
  spec/services/make_payment_spec.rb
  spec/support/debit_factory.rb
  spec/support/mocked_responses.rb
Labels: documentation

#179 Use temporary mocked responses from `DebitsApiResponses` module
  app/api_wrappers/debits_api.rb
  app/api_wrappers/debits_api_responses.rb
Labels: bug

#180 Add more tests to Direct Debit flow
  app/api_wrappers/debits_api.rb
  app/api_wrappers/payments_api.rb
  app/controllers/debits_controller.rb
  app/models/direct_debit.rb
  app/models/direct_debit_details.rb
  app/models/mandate.rb
  app/models/user.rb
  features/debits.feature
  features/payments.feature
  features/step_definitions/debits_steps.rb
  features/step_definitions/helper_steps.rb
  features/step_definitions/payments_steps.rb
  spec/api_wrappers/debits_api/caz_mandates_spec.rb
  spec/fixtures/responses/debits/active_mandates.json
  spec/fixtures/responses/debits/add_mandate.json
  spec/fixtures/responses/debits/caz_mandates.json
  spec/fixtures/responses/debits/create_mandate.json
  spec/fixtures/responses/debits/create_payment.json
  spec/fixtures/responses/debits/inactive_caz_mandates.json
  spec/fixtures/responses/debits/inactive_mandates.json
  spec/fixtures/responses/debits/mandates.json
  spec/models/direct_debit_details_spec.rb
  spec/models/direct_debit_spec.rb
  spec/models/mandate_spec.rb
  spec/requests/debits/confirm_spec.rb
  spec/requests/debits/create_spec.rb
  spec/requests/debits/first_mandate_spec.rb
  spec/requests/debits/initiate_spec.rb
  spec/services/make_card_payment_spec.rb
  spec/services/make_debit_payment_spec.rb
  spec/support/mocked_responses.rb
Labels: documentation
