Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2020-10, with the labels that each got.

#619 [CAZB-3184] Fix when making payment whilst upload is processing
  app/controllers/concerns/chargeability_calculator.rb
  app/controllers/payments/payments_controller.rb
  spec/requests/payments/payments/local_authority_spec.rb
  spec/requests/payments/payments/matrix_spec.rb
  spec/requests/vehicles_management/fleets/index_spec.rb
Labels: bug

#631 [CAZB-2669, CAZB-2637] Align error message for password complexity
  app/controllers/passwords_controller.rb
  app/forms/update_password_form.rb
  app/forms/users_management/set_up_account_form.rb
  app/services/account_details/update_email.rb
  config/locales/en.yml
  features/account_details/emails.feature
  features/account_details/passwords.feature
  features/passwords/password_reset.feature
  features/passwords/password_update.feature
  features/users_management/account_set_up.feature
  spec/forms/update_password_form_spec.rb
  spec/forms/users_management/set_up_account_form_spec.rb
  spec/requests/account_details/passwords/update_spec.rb
  spec/requests/passwords/create_spec.rb
  spec/requests/passwords/update_spec.rb
  spec/requests/users_management/create_users/confirm_set_up_spec.rb
  spec/services/account_details/update_email_spec.rb
Labels: documentation

#634 [CAZB-2972] Use errorCode from login endpoint
  Gemfile.lock
  app/api_wrappers/accounts_api/auth.rb
  config/locales/en.yml
  features/sign_in.feature
  features/step_definitions/sign_in_steps.rb
  lib/devise/models/remote_authenticatable.rb
  lib/devise/strategies/remote.rb
  spec/requests/sign_in_spec.rb
Labels: documentation

#635 [CAZB-2669] Sign in user after email change
  Gemfile
  Gemfile.lock
  app/api_wrappers/accounts_api/auth.rb
  app/controllers/account_details/emails_controller.rb
  app/services/account_details/update_email.rb
  config/cucumber.yml
  features/account_details/emails.feature
  features/step_definitions/account_details/emails_steps.rb
  features/step_definitions/dashboard_steps.rb
  features/step_definitions/path_expectations.rb
  spec/requests/account_details/emails/confirm_email_spec.rb
  spec/requests/account_details/emails/validate_confirm_email_spec.rb
Labels: documentation

#636 [CAZB-3273] Change email regexp
  .rubocop.yml
  app/api_wrappers/api_exception.rb
  app/api_wrappers/base_api.rb
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/forms/base_form.rb
  app/helpers/application_helper.rb
  app/helpers/fleets_helper.rb
  app/helpers/payments_helper.rb
  app/helpers/users_helper.rb
  app/services/session_manipulation/base_manipulator.rb
  config/application.rb
  features/step_definitions/sign_in_steps.rb
  features/support/helpers.rb
  features/support/mock_debit.rb
  features/support/mock_fleet.rb
  features/support/mock_payments.rb
  features/support/mock_users.rb
  features/support/mock_vccs.rb
  features/support/sign_in_helper.rb
  lib/devise/models/remote_authenticatable.rb
  spec/forms/users_management/add_user_form_spec.rb
  spec/requests/sign_in_spec.rb
Labels: bug

#637 [CAZB-3184] Check upload job status on the CAZ selection page
  app/controllers/payments/payments_controller.rb
  features/vehicles_management/uploads.feature
  spec/requests/payments/payments/index_spec.rb
Labels: bug

#641 Update .drone2.yml to use fixed sonar image version
  .drone2.yml
Labels: bug

#642 Add id's for the account details flow
  app/views/account_details/emails/confirm_email.html.haml
  app/views/account_details/emails/edit_email.html.haml
  app/views/account_details/names/edit_name.html.haml
  app/views/account_details/non_primary_users/non_primary_account_details.html.haml
  app/views/account_details/organisation_names/edit_name.html.haml
  app/views/account_details/passwords/edit.html.haml
  app/views/account_details/primary_users/primary_account_details.html.haml
Labels: documentation

#645 [CAZB-3273] Allow all uppercase email letters
  Gemfile.lock
  app/forms/base_form.rb
  spec/forms/users_management/add_user_form_spec.rb
Labels: bug

#646 [CAZB-3279] Update privacy label
  app/views/layouts/_footer.html.haml
  features/static_pages.feature
Labels: bug

#649 [CAZB-3352] Redirect to the failure page on duplicated dd payment
  app/controllers/direct_debits/debits_controller.rb
  spec/requests/direct_debits/debits/initiate_spec.rb
Labels: bug

#651 [CAZB-2669] Update label text on the confirm email page
  app/views/account_details/emails/confirm_email.html.haml
Labels: bug

#654 [CAZB-2639] Redirect to the account details when save no changes
  app/controllers/account_details/emails_controller.rb
  spec/requests/account_details/emails/edit_email_spec.rb
  spec/requests/account_details/emails/update_email_spec.rb
Labels: bug

#659 [CAZB: 3236, 3237, 3238] Update content
  app/views/organisations/organisations/cannot_create.html.haml
  app/views/organisations/organisations/fleet_check.html.haml
  app/views/organisations/organisations/new.html.haml
  config/locales/en.yml
  features/account_details/primary_user.feature
  features/organisations.feature
  features/step_definitions/organisations_steps.rb
Labels: documentation

#662 [CAZB-3257] Add 'onlyChargeable' toggle on the Fleet management page
  Gemfile
  Gemfile.lock
  app/api_wrappers/fleets_api.rb
  app/api_wrappers/payment_history_api.rb
  app/controllers/application_controller.rb
  app/controllers/vehicles_management/fleets_controller.rb
  app/models/vehicles_management/fleet.rb
  app/services/organisations/verify_account.rb
  app/views/passwords/index.html.haml
  app/views/vehicles_management/fleets/_pagination.html.haml
  app/views/vehicles_management/fleets/index.html.haml
  config/i18n-tasks.yml
  config/locales/en.yml
  spec/api_wrappers/fleets_api/vehicles_spec.rb
  spec/helpers/payments_helpers_spec.rb
  spec/i18n_spec.rb
  spec/models/manage_vehicles/fleet_spec.rb
  spec/requests/dashboard_spec.rb
  spec/requests/organisations/email_verification_spec.rb
  spec/spec_helper.rb
Labels: documentation

#666 Set `only_chargeable` default as false
  app/api_wrappers/fleets_api.rb
Labels: bug

#669 [CAZB: 3287, 3289, 3296, 3299] Update content
  app/models/user.rb
  app/views/dashboard/_company_payment_history.html.haml
  app/views/payment_history/payment_history/company_payment_history.html.haml
  app/views/users_management/create_users/new.html.haml
  app/views/users_management/edit_users/edit.html.haml
  app/views/vehicles_management/fleets/delete.html.haml
  app/views/vehicles_management/fleets/submission_method.html.haml
  config/locales/en.yml
  features/payments.feature
  features/step_definitions/dashboard_steps.rb
  features/step_definitions/payment_history_steps.rb
  features/step_definitions/users_management/manage_users_steps.rb
  features/step_definitions/vehicles_management/fleets_steps.rb
  features/support/mock_users.rb
  features/users_management/edit_user.feature
  spec/requests/organisations/email_sent_spec.rb
  spec/requests/organisations/resend_email_spec.rb
  spec/requests/payment_history/company_payment_history_spec.rb
  spec/requests/sign_in_spec.rb
  spec/requests/users_management/create_users/create_spec.rb
  spec/requests/users_management/create_users/new_spec.rb
  spec/requests/vehicles_management/fleets/delete_spec.rb
  spec/requests/vehicles_management/fleets/submission_method_spec.rb
  spec/requests/vehicles_management/fleets/submit_method_spec.rb
  spec/support/users_factory.rb
Labels: documentation

#676 [CAZB-3380] Add the Help page
  .drone2.yml
  .env.example
  Dockerfile.test
  Gemfile.lock
  app/controllers/static_pages_controller.rb
  app/models/clean_air_zone.rb
  app/views/dashboard/_help.html.haml
  app/views/layouts/_navbar.haml
  app/views/static_pages/help.html.haml
  app/views/vehicles_management/fleets/index.html.haml
  config/application.rb
  config/routes.rb
  features/dashboard/user_dashboard.feature
  features/static_pages.feature
  features/step_definitions/static_pages_steps.rb
  spec/models/clean_air_zones_spec.rb
  spec/requests/static_pages_spec.rb
  yarn.lock
Labels: documentation

#680 [CAZB: 3305, 3308, 3309, 3310] Update content
  .rubocop.yml
  app/api_wrappers/base_api.rb
  app/controllers/organisations/organisations_controller.rb
  app/exceptions/csv_upload_exception.rb
  app/forms/account_details/edit_user_email_form.rb
  app/forms/account_details/edit_user_name_form.rb
  app/forms/login_form.rb
  app/forms/new_password_form.rb
  app/forms/organisations/company_name_form.rb
  app/forms/token_form.rb
  app/forms/update_password_form.rb
  app/forms/users_management/add_user_permissions_form.rb
  app/forms/users_management/edit_user_form.rb
  app/forms/users_management/new_user_base_form.rb
  app/forms/users_management/set_up_account_form.rb
  app/forms/vehicles_management/submission_method_form.rb
  app/models/clean_air_zone.rb
  app/models/payment_history/details_payment.rb
  app/models/payment_history/paginated_payment.rb
  app/models/payments/details.rb
  app/models/vehicles_management/chargeable_fleet.rb
  app/models/vehicles_management/paginated_fleet.rb
  app/services/account_details/update_company_name.rb
  app/services/account_details/update_email.rb
  app/services/encryption/decrypt.rb
  app/services/encryption/encrypt.rb
  app/services/organisations/create_account.rb
  app/services/organisations/validate_fleet_check.rb
  app/services/organisations/verify_account.rb
  app/services/payment_history/back_link_history.rb
  app/services/payments/make_card_payment.rb
  app/services/payments/make_debit_payment.rb
  app/services/payments/payment_dates.rb
  app/services/session_manipulation/add_caz_id.rb
  app/services/session_manipulation/base_manipulator.rb
  app/services/session_manipulation/set_payment_details.rb
  app/views/vehicles_management/uploads/_description.html.haml
  app/views/vehicles_management/uploads/_reupload.html.haml
  app/views/vehicles_management/uploads/_upload.html.haml
  app/views/vehicles_management/uploads/calculating_chargeability.html.haml
  app/views/vehicles_management/uploads/index.html.haml
  app/views/vehicles_management/uploads/processing.html.haml
  db/seeds.rb
  features/step_definitions/vehicles_management/uploads_step.rb
  features/vehicles_management/uploads.feature
  lib/devise/models/remote_authenticatable.rb
  lib/devise/strategies/remote.rb
  lib/rubocop/blacklist.yml
  spec/requests/vehicles_management/uploads/index_spec.rb
  spec/requests/vehicles_management/uploads/processing_spec.rb
Labels: documentation

#684 [CAZB-3414] Update content on the confirm email page
  Gemfile.lock
  app/views/account_details/emails/confirm_email.html.haml
Labels: documentation

#685 [CAZB: 3304, 3311, 3314] Update content
  app/views/direct_debits/debits/index.html.haml
  app/views/payments/payments/failure.html.haml
  app/views/payments/payments/no_chargeable_vehicles.html.haml
  app/views/vehicles_management/uploads/calculating_chargeability.html.haml
Labels: documentation

#690 [CAZB: 3316, 3288, 3291] Update content
  Gemfile.lock
  app/models/vehicles_management/vehicle_details.rb
  app/views/account_details/passwords/edit.html.haml
  app/views/passwords/edit.html.haml
  app/views/users_management/create_users/confirmation.html.haml
  app/views/vehicles_management/vehicles/details.html.haml
  features/passwords/password_update.feature
  package.json
  spec/models/manage_vehicles/vehicle_details_spec.rb
  yarn.lock
Labels: documentation

#691 [CAZB-3257] Use only chargeable toggle when navigating through paged
  Gemfile.lock
  app/views/vehicles_management/fleets/_pagination_button.html.haml
Labels: documentation

#692 [CAZB-3257] Fix typo
  app/views/vehicles_management/fleets/index.html.haml
Labels: documentation

#693 [CAZB: 3446, 3447] Add links
  app/views/devise/sessions/new.html.haml
  app/views/organisations/organisations/new.html.haml
Labels: documentation

#699 [CAZB-3314] Payment unsuccessful - content updates
  app/views/direct_debits/debits/failure.html.haml
Labels: documentation

#705 Redirect user to the calculating page if uploading large fleet
  app/controllers/vehicles_management/vehicles_controller.rb
  app/views/vehicles_management/vehicles/local_exemptions.html.haml
  features/vehicles_management/uploads.feature
Labels: bug

#711 [CAZB-3459] Toggle content of "Accounts are for multiple vehicles"
  .env.example
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/concerns/chargeability_calculator.rb
  app/controllers/concerns/disable_payment_features.rb
  app/controllers/organisations/organisations_controller.rb
  app/models/user.rb
  app/views/organisations/organisations/cannot_create.html.haml
  config/application.rb
  features/step_definitions/organisations_steps.rb
  features/vehicles_management/fleets.feature
  spec/fixtures/responses/caz_list.json
  spec/fixtures/responses/caz_list_active.json
  spec/models/clean_air_zones_spec.rb
  spec/requests/organisations/cannot_create_spec.rb
  spec/spec_helper.rb
Labels: documentation

#712 [CAZB-3448] Manage vehicles - content update for "A-day"
  app/controllers/concerns/payment_features.rb
  app/controllers/organisations/organisations_controller.rb
  app/controllers/vehicles_management/fleets_controller.rb
  app/views/organisations/organisations/cannot_create.html.haml
  app/views/vehicles_management/fleets/_charge_cannot_be_calculated.html.haml
  app/views/vehicles_management/fleets/index.html.haml
Labels: documentation

#713 [CAZB-3499] Update retrofit scheme URL pointer
  app/views/static_pages/help.html.haml
Labels: enhancement
