Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2020-07, with the labels that each got.

#374 [CAZ-2400] Hide manage link for current user
  app/helpers/users_helper.rb
  app/models/manage_users/user.rb
  app/views/users/index.html.haml
  features/support/mock_users.rb
  spec/models/manage_users/user_spec.rb
Labels: bug

#379 Fix yarn audit warning
  .drone.yml
Labels: bug

#377 [CAZB-2151] Unauthorized 'Make payment' protection
  .rubocop.yml
  Gemfile.lock
  app/api_wrappers/api_exception.rb
  app/controllers/debits_controller.rb
  app/controllers/payments_controller.rb
  app/controllers/users_controller.rb
  app/forms/search_vrn_form.rb
  app/services/create_user_account.rb
  app/views/debits/cancel.html.haml
  config/initializers/filter_parameter_logging.rb
  config/routes.rb
  features/debits.feature
  features/step_definitions/debits_steps.rb
  package.json
  spec/forms/search_vrn_form_spec.rb
  spec/helpers/check_permissions_helpers_spec.rb
  spec/rails_helper.rb
  spec/requests/debits/cancel_spec.rb
  spec/requests/fleets/index_spec.rb
  spec/requests/payments/cancel_spec.rb
  spec/requests/payments/clear_search_spec.rb
  spec/requests/payments/confirm_payment_method_spec.rb
  spec/requests/payments/index_spec.rb
  spec/requests/payments/local_authority_spec.rb
  spec/requests/payments/matrix_spec.rb
  spec/requests/payments/select_payment_method_spec.rb
  spec/requests/payments/submit_spec.rb
  yarn.lock
Labels: documentation

#378 [CAZB-1942] Send vehicle type to accounts api when adding vehicle
  app/api_wrappers/fleets_api.rb
  app/controllers/vehicles_management/vehicles_controller.rb
  app/models/vehicles_management/fleet.rb
  spec/api_wrappers/fleets_api/add_vehicle_to_fleet_spec.rb
  spec/models/manage_vehicles/fleet_spec.rb
  spec/requests/manage_vehicles/vehicles/add_to_fleet_spec.rb
  spec/requests/manage_vehicles/vehicles/confirm_and_add_exempt_vehicle_to_fleet_spec.rb
Labels: don't merge

#387 Fix pa11y test
  app/views/static_pages/accessibility_statement.html.haml
  pa11y/.pa11yci.conf.js
Labels: bug

#390 Uncomment Pa11y test after it was fixed on dev
  pa11y/.pa11yci.conf.js
Labels: bug

#400 [CAZB-2144] User removal confirmation
  Gemfile.lock
  app/api_wrappers/accounts_api.rb
  app/controllers/users_management/edit_users_controller.rb
  app/controllers/users_management/remove_users_controller.rb
  app/forms/new_user_base_form.rb
  app/helpers/users_helper.rb
  app/services/organisations/create_account.rb
  app/views/users_management/edit_users/edit.html.haml
  app/views/users_management/remove_users/delete.haml
  app/views/users_management/remove_users/remove.haml
  app/views/users_management/users/index.html.haml
  config/initializers/amazon_s3_client.rb
  config/locales/en.yml
  config/routes.rb
  features/step_definitions/users_management/manage_users_steps.rb
  features/step_definitions/users_management/remove_user_steps.rb
  features/support/mock_users.rb
  features/users_management/remove_user.feature
  spec/api_wrappers/accounts_api/delete_user_spec.rb
  spec/forms/email_and_password_form_spec.rb
  spec/requests/users_management/edit_users/edit_spec.rb
  spec/requests/users_management/edit_users/update_spec.rb
  spec/requests/users_management/remove_users/confirm_remove_spec.rb
  spec/requests/users_management/remove_users/remove_spec.rb
  spec/support/users_factory.rb
  spec/support/users_management/mocked_responses.rb
  yarn.lock
Labels: documentation

#404 [CAZB-2144] Fix design on the user removal page
  app/controllers/users_management/remove_users_controller.rb
  app/views/users_management/remove_users/remove.haml
Labels: bug

#402 [CAZB-2141] Account set up confirmation page
  app/views/devise/sessions/new.html.haml
  app/views/organisations/organisations/email_verified.haml
  app/views/shared/sign_in/_email_field.html.haml
  app/views/shared/sign_in/_error_summary.html.haml
  app/views/shared/sign_in/_password_field.html.haml
  app/views/users_management/create_users/set_up_confirmation.html.haml
  config/initializers/devise.rb
  features/sign_in.feature
  features/step_definitions/sign_in_steps.rb
  lib/custom_failure.rb
  spec/requests/sign_in_spec.rb
Labels: documentation

#408 [CAZB-2144] Fix back button on the user removal page
  app/controllers/users_management/remove_users_controller.rb
  app/views/users_management/remove_users/remove.haml
  features/users_management/remove_user.feature
Labels: bug

#410 [CAZB-2365] Dynamic company name on account set up page
  Gemfile
  Gemfile.lock
  app/api_wrappers/accounts_api.rb
  app/controllers/users_management/create_users_controller.rb
  app/views/users_management/create_users/set_up.html.haml
  config/initializers/filter_parameter_logging.rb
  features/step_definitions/users_steps.rb
  features/users_management/account_set_up.feature
  spec/requests/users_management/create_users/confirm_set_up_spec.rb
  spec/requests/users_management/create_users/set_up_spec.rb
Labels: documentation

#412 Fix verification_url when sending set up link to user
  app/controllers/users_management/create_users_controller.rb
Labels: bug

#415 [CAZ-2400] Rename 'Manage' link to 'Change'
  app/views/users_management/users/index.html.haml
  features/users_management/edit_user.feature
  features/users_management/manage_users.feature
  features/users_management/remove_user.feature
Labels: documentation

#416 [CAZB-2143] Fix back button on the add permissions page
  app/views/users_management/create_users/add_permissions.html.haml
  app/views/users_management/create_users/set_up.html.haml
  config/routes.rb
  features/users_management/manage_users.feature
  spec/requests/users_management/create_users/confirm_set_up_spec.rb
  spec/requests/users_management/create_users/set_up_spec.rb
Labels: bug

#413 [CAZB-2161] Filter out removed users and owner from the users list
  Gemfile.lock
  app/controllers/dashboard_controller.rb
  app/controllers/users_management/create_users_controller.rb
  app/controllers/users_management/users_controller.rb
  app/services/users_management/users.rb
  app/views/users_management/users/index.html.haml
  features/step_definitions/users_management/manage_users_steps.rb
  features/support/mock_users.rb
  features/users_management/manage_users.feature
  spec/api_wrappers/accounts_api/users_spec.rb
  spec/fixtures/responses/users_management/users.json
  spec/forms/company_name_form_spec.rb
  spec/forms/confirmation_form_spec.rb
  spec/forms/email_and_password_form_spec.rb
  spec/forms/fleet_check_form_spec.rb
  spec/forms/login_form_spec.rb
  spec/forms/new_password_form_spec.rb
  spec/forms/payment_review_form_spec.rb
  spec/forms/reset_password_form_spec.rb
  spec/forms/set_up_account_form_spec.rb
  spec/forms/submission_method_form_spec.rb
  spec/forms/token_form_spec.rb
  spec/forms/vrn_form_spec.rb
  spec/helpers/application_helpers_spec.rb
  spec/helpers/payments_helpers_spec.rb
  spec/models/clean_air_zones_spec.rb
  spec/models/direct_debits/debit_spec.rb
  spec/models/direct_debits/mandate_spec.rb
  spec/models/manage_vehicles/chargeable_fleet_spec.rb
  spec/models/manage_vehicles/chargeable_vehicle_spec.rb
  spec/models/manage_vehicles/fleet_spec.rb
  spec/models/manage_vehicles/paginated_fleet_spec.rb
  spec/models/manage_vehicles/vehicle_details_spec.rb
  spec/models/manage_vehicles/vehicle_spec.rb
  spec/models/payments/details_spec.rb
  spec/models/payments/status_spec.rb
  spec/models/reset_password_form_spec.rb
  spec/models/user_spec.rb
  spec/requests/vehicles_management/fleets/confirm_delete_spec.rb
  spec/requests/vehicles_management/fleets/create_spec.rb
  spec/services/organisations/validate_fleet_check_spec.rb
  spec/services/payments/make_card_payment_spec.rb
  spec/services/payments/make_debit_payment_spec.rb
  spec/services/payments/payment_dates_spec.rb
  spec/services/users_management/users_spec.rb
  spec/services/vehicles_management/upload_file_spec.rb
  spec/support/shared_examples/invalid_vrn_form.rb
Labels: bug, documentation

#418 [CAZB-2155] Add payment history links to dashboard
  .drone.yml
  Gemfile.lock
  app/controllers/concerns/check_permissions.rb
  app/controllers/payment_history/payment_history_controller.rb
  app/controllers/sessions_controller.rb
  app/views/dashboard/_company_payment_history.html.haml
  app/views/dashboard/_user_payment_history.html.haml
  app/views/dashboard/index.html.haml
  app/views/payment_history/payment_history/company_payment_history.html.haml
  app/views/payment_history/payment_history/user_payment_history.html.haml
  config/routes.rb
  features/user_dashboard.feature
  package.json
  yarn.lock
Labels: documentation

#420 [CAZ-3091] Sort users by name and downcase email
  app/api_wrappers/base_api.rb
  app/models/users_management/user.rb
  app/services/users_management/users.rb
  spec/fixtures/responses/users_management/users.json
  spec/models/manage_users/user_spec.rb
  spec/services/users_management/users_spec.rb
Labels: documentation

#422 [CAZ-2413] Fix back button on the Add a new user page
  app/api_wrappers/accounts_api.rb
  app/controllers/users_management/create_users_controller.rb
  features/step_definitions/dashboard_steps.rb
  features/step_definitions/users_management/manage_users_steps.rb
  features/users_management/manage_users.feature
Labels: bug

#428 [CAZB-2144] Redirect to the edit user page when was chosen `No`
  .gitignore
  app/controllers/users_management/remove_users_controller.rb
  features/users_management/remove_user.feature
  spec/requests/users_management/remove_users/confirm_remove_spec.rb
Labels: bug

#429 [CAZB-2155] Update the user payment page title
  app/views/payment_history/payment_history/user_payment_history.html.haml
Labels: bug

#440 [CAZB-2144] Update error message on user removal page
  app/controllers/users_management/remove_users_controller.rb
  config/locales/en.yml
  features/users_management/remove_user.feature
  spec/requests/users_management/remove_users/confirm_remove_spec.rb
Labels: bug
