Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2020-08, with the labels that each got.

#445 [CAZB-2166] Fix back button on payment history details page
  Gemfile.lock
  app/controllers/dashboard_controller.rb
  app/controllers/payment_history/payment_history_controller.rb
  app/views/payment_history/payment_history/payment_history_details.html.haml
  features/payment_history.feature
  features/step_definitions/static_pages_steps.rb
Labels: bug

#446 [CAZB-2166] Fix back button on company and user history pages
  app/controllers/dashboard_controller.rb
  app/controllers/payment_history/payment_history_controller.rb
  app/services/back_link_history_service.rb
  features/payment_history.feature
  features/step_definitions/helper_steps.rb
  spec/services/back_link_history_service_spec.rb
Labels: bug

#447 Add and refactor tests
  app/controllers/payment_history/payment_history_controller.rb
  spec/api_wrappers/accounts_api/set_password_spec.rb
  spec/api_wrappers/accounts_api/user_invitations_spec.rb
  spec/api_wrappers/accounts_api/validate_password_reset_spec.rb
  spec/api_wrappers/debits_api/caz_mandates_spec.rb
  spec/api_wrappers/debits_api/create_mandate_spec.rb
  spec/api_wrappers/debits_api/mandates_spec.rb
  spec/api_wrappers/fleets_api/add_vehicle_to_fleet_spec.rb
  spec/api_wrappers/fleets_api/fleet_vehicles_spec.rb
  spec/api_wrappers/fleets_api/job_status_spec.rb
  spec/api_wrappers/fleets_api/register_job_spec.rb
  spec/api_wrappers/fleets_api/remove_vehicle_from_fleet_spec.rb
  spec/api_wrappers/payments_api/chargeable_vehicle_spec.rb
  spec/api_wrappers/payments_api/chargeable_vehicles_spec.rb
  spec/api_wrappers/payments_api/charges_spec.rb
  spec/api_wrappers/payments_api/create_payment_spec.rb
  spec/api_wrappers/payments_api/payment_status_spec.rb
  spec/forms/token_form_spec.rb
  spec/models/clean_air_zones_spec.rb
  spec/models/direct_debits/debit_spec.rb
  spec/models/direct_debits/details_spec.rb
  spec/models/direct_debits/mandate_spec.rb
  spec/models/manage_vehicles/chargeable_vehicle_spec.rb
  spec/models/manage_vehicles/fleet_spec.rb
  spec/models/manage_vehicles/vehicle_spec.rb
  spec/models/payment_history/details_payment_spec.rb
  spec/models/payments/details_spec.rb
  spec/models/payments/status_spec.rb
  spec/requests/passwords/create_spec.rb
  spec/requests/payment_history/payment_history_details_spec.rb
  spec/services/organisations/create_user_account_spec.rb
  spec/services/session_manipulation/add_la_id_spec.rb
  spec/services/session_manipulation/add_payment_details_spec.rb
  spec/services/session_manipulation/add_query_details_spec.rb
  spec/services/session_manipulation/set_payment_id_spec.rb
  spec/services/vehicles_management/upload_file_spec.rb
Labels: documentation

#449 Use double pipe and add test
  app/controllers/payment_history/payment_history_controller.rb
  spec/requests/users_management/users/index_spec.rb
Labels: documentation

#455 [CAZ-2400] Show himself on the list but without Change link
  app/helpers/users_helper.rb
  app/services/users_management/users.rb
  app/views/users_management/users/index.html.haml
  spec/services/users_management/users_spec.rb
Labels: bug

#459 [CAZB-2222] Hide `payment made by` on payment details history page
  app/controllers/payment_history/payment_history_controller.rb
  features/payment_history.feature
  features/step_definitions/payment_history_steps.rb
Labels: bug

#462 Update ST v1.2 with develop (selected commits)
  app/controllers/application_controller.rb
  app/controllers/payment_history/payment_history_controller.rb
  features/payment_history.feature
  features/step_definitions/payment_history_steps.rb
Labels: don't merge

#465 [CAZB-2335] Add configurable CSV size limit
  .env.example
  .rubocop.yml
  Gemfile.lock
  app/api_wrappers/accounts_api.rb
  app/api_wrappers/compliance_checker_api.rb
  app/api_wrappers/payments_api.rb
  app/controllers/users_management/create_users_controller.rb
  app/controllers/vehicles_management/fleets_controller.rb
  app/forms/company_name_form.rb
  app/helpers/application_helper.rb
  app/helpers/payments_helper.rb
  app/services/back_link_history_service.rb
  app/services/vehicles_management/upload_file.rb
  config/application.rb
  config/environments/production.rb
  features/dashboard/owner_dashboard.feature
  features/dashboard/user_dashboard.feature
  features/step_definitions/debits_steps.rb
  features/step_definitions/payments_steps.rb
  features/step_definitions/vehicles_management/fleets_steps.rb
  features/step_definitions/vehicles_management/uploads_step.rb
  features/step_definitions/vehicles_management/vehicles_steps.rb
  features/support/mock_fleet.rb
  features/vehicles_management/fleets.feature
  features/vehicles_management/uploads.feature
  features/vehicles_management/vehicles.feature
  spec/services/vehicles_management/upload_file_spec.rb
Labels: documentation

#466 [CAZB-2645] Hide disabled CAZes on Set up a Direct Debit page
  app/controllers/application_controller.rb
  app/models/direct_debits/debit.rb
  features/debits.feature
  features/step_definitions/debits_steps.rb
  features/step_definitions/payments_steps.rb
  spec/fixtures/responses/debits/active_mandates.json
  spec/fixtures/responses/debits/inactive_mandates.json
  spec/fixtures/responses/debits/mandates.json
  spec/models/direct_debits/debit_spec.rb
Labels: documentation

#472 Promote Accounts (Fleets) v1.1.1 to Production
  .drone2.yml
  .env.example
  app/controllers/application_controller.rb
Labels: Accounts v1.1.1, release

#502 [CAZB-2103] Add "calculating chargeability" screen after upload job
  Gemfile
  Gemfile.lock
  app/api_wrappers/fleets_api.rb
  app/controllers/application_controller.rb
  app/controllers/payments/payments_controller.rb
  app/controllers/vehicles_management/fleets_controller.rb
  app/controllers/vehicles_management/uploads_controller.rb
  app/views/vehicles_management/uploads/calculating_chargeability.html.haml
  config/locales/en.yml
  config/routes.rb
  features/step_definitions/vehicles_management/fleets_steps.rb
  features/step_definitions/vehicles_management/uploads_step.rb
  features/step_definitions/vehicles_management/vehicles_steps.rb
  features/support/sign_in_helper.rb
  features/vehicles_management/uploads.feature
  package.json
  spec/api_wrappers/fleets_api/job_status_spec.rb
  spec/requests/vehicles_management/uploads/create_spec.rb
  spec/requests/vehicles_management/uploads/processing_spec.rb
  yarn.lock
Labels: documentation

#506 Fix redis initializer
  app/controllers/application_controller.rb
  app/controllers/vehicles_management/uploads_controller.rb
  config/initializers/redis.rb
  features/step_definitions/vehicles_management/uploads_step.rb
  spec/requests/vehicles_management/uploads/create_spec.rb
  spec/requests/vehicles_management/uploads/processing_spec.rb
Labels: bug

#507 [CAZB-2866] Remove duplicated code and add more tests
  app/controllers/vehicles_management/uploads_controller.rb
  app/controllers/vehicles_management/vehicles_controller.rb
  features/vehicles_management/uploads.feature
  spec/requests/vehicles_management/fleets/index_spec.rb
  spec/requests/vehicles_management/uploads/processing_spec.rb
Labels: documentation
