Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2020-06, with the labels that each got.

#310 [CAZ-2786] Rename `admin` field to `owner`
  app/api_wrappers/accounts_api.rb
  app/controllers/application_controller.rb
  app/controllers/organisations_controller.rb
  app/models/user.rb
  config/initializers/assets.rb
  features/dashboard.feature
  features/sign_in.feature
  features/step_definitions/sign_in_steps.rb
  features/support/sign_in_helper.rb
  spec/api_wrappers/accounts_api/create_user_spec.rb
  spec/api_wrappers/accounts_api/sign_in_spec.rb
  spec/fixtures/responses/create_user.json
  spec/requests/fleets/create_spec.rb
  spec/requests/sign_in_spec.rb
  spec/requests/sign_out_spec.rb
  spec/services/create_user_account_spec.rb
  spec/support/user_factory.rb
Labels: documentation, don't merge

#312 [CAZ-2809] D-Day notice to not be displayed when does not apply
  app/api_wrappers/compliance_checker_api.rb
  app/views/payments/matrix.html.haml
  app/views/payments/matrix/_heading.html.haml
  app/views/payments/matrix/_next_week_tab.html.haml
  app/views/payments/matrix/_past_week_tab.html.haml
Labels: bug

#313 [NT] Remove memoization for `ComplianceCheckerApi.clean_air_zones` endpoint
  app/models/clean_air_zone.rb
  features/support/mock_vccs.rb
  spec/models/clean_air_zones_spec.rb
Labels: bug

#323 Fix `websocket-extensions` vulnerability
  Gemfile.lock
Labels: documentation

#325 [CAZ-2709] Show D-Day notice if it starting from today
  app/views/payments/matrix/_next_week_tab.html.haml
Labels: bug

#329 [CAZ-2809] Show D-Day notice if charge start day is today too
  app/services/payment_dates.rb
  features/payments.feature
  spec/services/payment_dates_spec.rb
Labels: bug

#337 Bump ruby and rails
  .rubocop.yml
  .ruby-version
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/credit_cards_controller.rb
  app/controllers/organisations_controller.rb
  app/controllers/payments_controller.rb
  app/controllers/uploads_controller.rb
  app/forms/company_name_form.rb
  app/helpers/application_helper.rb
  app/models/vehicle.rb
  app/services/payment_dates.rb
  features/step_definitions/fleets_steps.rb
  package.json
  spec/rails_helper.rb
  spec/requests/uploads/download_template_spec.rb
  spec/services/payment_dates_spec.rb
  yarn.lock
Labels: documentation

#338 [CAZ-2909] Update D-Day notice
  app/services/payment_dates.rb
  app/views/payments/matrix.html.haml
  app/views/payments/matrix/_details.html.haml
  app/views/payments/matrix/_next_week_tab.html.haml
  app/views/payments/matrix/_past_week_tab.html.haml
  features/payments.feature
  spec/services/payment_dates_spec.rb
Labels: documentation

#342 [CAZ-2909] Update D-Day notice
  app/services/payment_dates.rb
  spec/services/payment_dates_spec.rb
Labels: documentation

#345 [CAZ-2656] Remove D-Day notice from past and next week tabs
  app/views/payments/matrix/_next_week_tab.html.haml
  app/views/payments/matrix/_past_week_tab.html.haml
Labels: documentation

#350 [CAZ-2413] Add user permissions support
  .rubocop.yml
  Gemfile.lock
  app/api_wrappers/accounts_api.rb
  app/api_wrappers/base_api.rb
  app/controllers/concerns/check_permissions.rb
  app/controllers/credit_cards_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/debits_controller.rb
  app/controllers/fleets_controller.rb
  app/controllers/organisations_controller.rb
  app/controllers/payments_controller.rb
  app/controllers/uploads_controller.rb
  app/controllers/users_controller.rb
  app/controllers/vehicles_controller.rb
  app/helpers/check_permissions_helper.rb
  app/helpers/fleets_helper.rb
  app/models/user.rb
  app/views/dashboard/_manage_users.html.haml
  app/views/dashboard/index.html.haml
  app/views/users/index.html.haml
  app/views/users/new.html.haml
  config/initializers/amazon_s3_client.rb
  config/initializers/content_security_policy.rb
  config/puma.rb
  config/routes.rb
  features/fleets.feature
  features/owner_dashboard.feature
  features/sign_in.feature
  features/step_definitions/dashboard_steps.rb
  features/step_definitions/debits_steps.rb
  features/step_definitions/fleets_steps.rb
  features/step_definitions/helper_steps.rb
  features/step_definitions/payments_steps.rb
  features/step_definitions/sign_in_steps.rb
  features/step_definitions/uploads_step.rb
  features/step_definitions/vehicles_steps.rb
  features/support/mock_debit.rb
  features/support/mock_users.rb
  features/support/sign_in_helper.rb
  features/user_dashboard.feature
  spec/api_wrappers/accounts_api/create_user_spec.rb
  spec/api_wrappers/accounts_api/sign_in_spec.rb
  spec/api_wrappers/accounts_api/users_spec.rb
  spec/fixtures/responses/create_user.json
  spec/fixtures/responses/manage_users/users.json
  spec/requests/dashboard_spec.rb
  spec/support/mocked_responses.rb
  spec/support/user_factory.rb
Labels: documentation

#360 [CAZ-2402] Add User Page
  app/api_wrappers/accounts_api.rb
  app/controllers/users_controller.rb
  app/forms/new_user_form.rb
  app/services/session_manipulation/set_new_user.rb
  app/views/users/add_permissions.html.haml
  app/views/users/new.html.haml
  app/views/users/new_user_form_input/_errored.html.haml
  app/views/users/new_user_form_input/_normal.html.haml
  config/locales/en.yml
  config/routes.rb
  spec/api_wrappers/accounts_api/user_validations_spec.rb
  spec/services/session_manipulation/set_new_user_spec.rb
Labels: documentation
