Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2021-03, with the labels that each got.

#950 [CAZB-4178] Prevent filtering of active CAZs for beta group
  app/api_wrappers/debits_api.rb
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/helpers/application_helper.rb
  app/models/direct_debits/debit.rb
  features/dashboard/owner_dashboard.feature
  features/step_definitions/dashboard_steps.rb
  spec/models/direct_debits/debit_spec.rb
  spec/requests/dashboard_controller_spec.rb
  spec/support/users_factory.rb
Labels: documentation

#953 [CAZB-3873] Sort refunds/chargebacks alphabetically by vrn
  app/models/payment_history/details.rb
  spec/fixtures/responses/payment_history/payment_details.json
  spec/models/payment_history/details_spec.rb
Labels: documentation

#973 [CAZB-4267] User in "loop" when making payment when only one caz is available
  app/api_wrappers/compliance_checker_api.rb
  app/controllers/payments/payments_controller.rb
  app/models/clean_air_zone.rb
  app/views/payments/payments/in_progress.html.haml
  features/payments.feature
  features/step_definitions/vehicles_management/fleets_steps.rb
  features/support/mock_vccs.rb
  spec/models/clean_air_zones_spec.rb
Labels: documentation

#975 [CAZB-4004] Replace `Charge back` to `Chargeback`
  app/views/payment_history/payment_history/payment_history_details.html.haml
  features/payment_history.feature
Labels: documentation

#978 [CAZB-4267] User in "loop" when making payment
  app/controllers/payments/payments_controller.rb
  app/models/clean_air_zone.rb
  spec/models/clean_air_zones_spec.rb
Labels: documentation

#993 [CAZB-4272] Correct D-Day content for 'Previous days' on matrix page
  .drone2.yml
  Gemfile.lock
  app/controllers/payments/payments_controller.rb
  app/helpers/payments_helper.rb
  app/services/payments/payment_dates.rb
  app/views/payments/payments/matrix/_past_week_tab.html.haml
  app/views/payments/payments/matrix/_tabs.html.haml
  features/payments.feature
  package.json
  spec/requests/payments/payments/matrix_spec.rb
  spec/services/payments/payment_dates_spec.rb
  yarn.lock
Labels: bug

#996 [NON-JIRA] Remove clean agent step in dev to allow image caching
  .drone2.yml
Labels: enhancement

#1002 [CAZB-4346] Display all Clean Air Zone listings if member of beta group
  Gemfile.lock
  app/api_wrappers/accounts_api/accounts.rb
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/vehicles_management/fleets_controller.rb
  app/helpers/application_helper.rb
  app/models/direct_debits/debit.rb
  app/models/user.rb
  features/step_definitions/vehicles_management/fleets_steps.rb
  features/vehicles_management/fleets.feature
  spec/api_wrappers/accounts_api/accounts/csv_exports_spec.rb
Labels: dependencies
