Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2021-05, with the labels that each got.

#1072 [CAZB-3993] Update error message on accessing accounts URL/fleets
  .drone2.yml
  app/controllers/payment_history/payment_history_controller.rb
  app/services/encryption/base.rb
  app/views/devise/sessions/new.html.haml
  app/views/shared/sign_in/_email_field.html.haml
  app/views/shared/sign_in/_error_summary.html.haml
  app/views/shared/sign_in/_password_field.html.haml
  ci-cd-resources/check_build_number.sh
  ci-cd-resources/pa11y/.gitignore
  ci-cd-resources/pa11y/.pa11yci.conf.js
  ci-cd-resources/pa11y/Dockerfile
  ci-cd-resources/pa11y/Makefile
  config/locales/devise.en.yml
  features/sign_in.feature
  features/step_definitions/sign_in_steps.rb
  lib/devise/strategies/remote.rb
  storage/.keep
Labels: documentation

#1086 [CAZB-4099] Update navigation bar
  .drone2.yml
  .rubocop.yml
  .scss-lint.yml
  .stylelintrc.json
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/javascript/src/govukFrontendAssets.js
  app/javascript/src/hmrcFrontendAssets.js
  app/javascript/src/printLink/styles.scss
  app/javascript/styles/application.scss
  app/javascript/styles/cookie_control.scss
  app/javascript/styles/custom_pagination.scss
  app/views/layouts/_header.html.haml
  app/views/layouts/_navbar.haml
  app/views/layouts/application.html.haml
  app/views/layouts/disabled_links/_header.html.haml
  app/views/layouts/disabled_links/_navbar.haml
  app/views/layouts/disabled_links/application.html.haml
  features/sign_in.feature
  package.json
  yarn.lock
Labels: documentation

#1087 Promote Accounts v2.3.2 to Production
  .drone2.yml
  .rubocop.yml
  .ruby-version
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrappers/accounts_api/payment_history.rb
  app/controllers/payment_history/payment_history_controller.rb
  app/forms/vrn_form.rb
  app/models/aws_signed_url.rb
  app/models/payment_history/export_status.rb
  app/services/payment_history/initiate_payment_history_export.rb
  app/services/payment_history/parse_file_name.rb
  app/views/account_details/account_cancellations/account_closing_notice.html.haml
  app/views/devise/sessions/new.html.haml
  app/views/payment_history/payment_history/_payment_modifications.html.haml
  app/views/payment_history/payment_history/payment_history.html.haml
  app/views/payment_history/payment_history/payment_history_details.html.haml
  app/views/payment_history/payment_history/payment_history_download.html.haml
  app/views/payment_history/payment_history/payment_history_downloading.html.haml
  app/views/payment_history/payment_history/payment_history_link_expired.html.haml
  app/views/payments/payments/matrix/_table.html.haml
  config/routes.rb
  features/payment_history/payment_history.feature
  features/payment_history/payment_history_download.feature
  features/step_definitions/payment_history_steps.rb
  features/support/mock_payments.rb
  lib/devise/strategies/remote.rb
  package.json
  spec/api_wrappers/accounts_api/payment_history/payment_history_export_spec.rb
  spec/api_wrappers/accounts_api/payment_history/payment_history_export_status_spec.rb
  spec/fixtures/responses/payment_history/export_status.json
  spec/forms/vrn_form_spec.rb
  spec/models/aws_signed_url_spec.rb
  spec/models/payment_history/export_status_spec.rb
  spec/requests/payment_history/handle_payment_history_download_attempt_spec.rb
  spec/requests/payment_history/initiate_payment_history_download_spec.rb
  spec/requests/payment_history/payment_history_download_spec.rb
  spec/requests/payment_history/payment_history_downloading_spec.rb
  spec/requests/payment_history/payment_history_link_expired_spec.rb
  spec/services/payment_history/back_link_history_spec.rb
  spec/services/payment_history/initiate_payment_history_export_spec.rb
  spec/services/payment_history/parse_file_name_spec.rb
  spec/services/vehicles_management/dynamic_cazes/select_caz_spec.rb
  yarn.lock
Labels: Accounts v2.3.2, dont merge yet, release

#1097 [CAZB-4878] Minor typography correction
  app/views/vehicles_management/vehicles/not_found.html.haml
Labels: bug

#1102 [CAZB-4885] Update content on CAZ selection page
  app/views/payments/payments/index.html.haml
Labels: enhancement

#1106 [CAZB-4917] Fix Account Pay survey link
  .drone2.yml
Labels: bug

#1110 [CAZB-4934] Disable DD payment selection based on CAZ specific flags
  .drone2.yml
  .iyarc
  README.md
  app/controllers/payments/payments_controller.rb
  app/views/payments/payments/review.html.haml
  features/payments.feature
  features/step_definitions/vehicles_management/fleets_steps.rb
  spec/requests/payments/payments/confirm_review_spec.rb
  spec/requests/payments/payments/review_spec.rb
  spec/requests/payments/payments/select_payment_method_spec.rb
Labels: documentation

#1112 [CAZB-4934] Enable DD payment selection if user is beta tester
  app/controllers/payments/payments_controller.rb
  app/models/payments/constants.rb
  spec/requests/payments/payments/review_spec.rb
Labels: documentation

#1108 Staging
  .drone2.yml
  app/controllers/application_controller.rb
  app/exceptions/invalid_host_exception.rb
  app/services/security/host_header_validator.rb
  config/application.rb
  spec/services/security/host_header_validator_spec.rb
Labels: Accounts 2.3.4, dont merge yet

#1118 Promote Account 2.3.7 to Staging
  app/views/payments/payments/index.html.haml
  app/views/relevant_portal/what_would_you_like_to_do.html.haml
  app/views/static_pages/help.html.haml
Labels: Accounts v2.3.7

#1120 [CAZB-4953] Update error positioning on triage page (#1116)
  app/views/relevant_portal/what_would_you_like_to_do.html.haml
Labels: enhancement

#1121 [CAZB-4383] Adjust total Amount paid display
  app/models/payment_history/payment.rb
  app/views/payment_history/payment_history/payment_history.html.haml
  spec/fixtures/responses/payment_history/payments.json
  spec/models/payment_history/payment_spec.rb
Labels: documentation
