Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2021-06, with the labels that each got.

#1119 Promote Accounts 2.3.7 to Production
  app/views/payments/payments/index.html.haml
  app/views/relevant_portal/what_would_you_like_to_do.html.haml
  app/views/static_pages/help.html.haml
Labels: Accounts 2.3.7

#1141 [CAZB-4374] Hide cookie control on `what would you like to do` page?
  .iyarc
  Gemfile.lock
  app/javascript/packs/application.js
  app/views/layouts/_footer.html.haml
  app/views/layouts/application.html.haml
  app/views/layouts/disabled_links/_footer.html.haml
  features/relevant_portal.feature
  package.json
  yarn.lock
Labels: bug, documentation

#1152 [CAZB-4906] Validate user names against blacklisted characters
  app/controllers/users_management/edit_users_controller.rb
  app/forms/users_management/add_user_form.rb
  config/locales/en.yml
  spec/forms/users_management/add_user_form_spec.rb
Labels: documentation

#1159 [CAZB-4374] Disable session cookies on `what would you like to do` page
  app/controllers/relevant_portal_controller.rb
Labels: bug

#1164 [CAZB-4686] Update "manage_vehicles/remove" page
  .iyarc
  Gemfile.lock
  app/controllers/vehicles_management/fleets_controller.rb
  app/views/vehicles_management/fleets/remove.html.haml
  features/step_definitions/vehicles_management/fleets_steps.rb
  features/vehicles_management/fleets.feature
  package.json
  spec/requests/vehicles_management/fleets/confirm_remove_spec.rb
  yarn.lock
Labels: documentation

#1172 [CAZB-4896] Fix javascript after implementation nonces
  .drone2.yml
  .eslintrc.json
  README.md
  app/javascript/channels/consumer.js
  app/javascript/channels/index.js
  app/javascript/packs/application.js
  app/javascript/packs/autorefreshPage.js
  app/javascript/packs/exportButtonNotice.js
  app/javascript/packs/paymentMatrix.js
  app/javascript/packs/payment_history/perPage.js
  app/javascript/packs/redirectToTimeoutNotice.js
  app/javascript/packs/resendLink.js
  app/javascript/packs/timeoutLogout.js
  app/javascript/packs/vehicles_management/onlyChargeable.js
  app/javascript/packs/vehicles_management/perPage.js
  app/javascript/src/backLink.js
  app/javascript/src/backLink/init.js
  app/javascript/src/cookieControl.js
  app/javascript/src/paymentMatrix/createHiddenInput.js
  app/javascript/src/paymentMatrix/emptyMatrixContinuePrevention.js
  app/javascript/src/paymentMatrix/initPaginationButton.js
  app/javascript/src/paymentMatrix/initSearch.js
  app/javascript/src/paymentMatrix/submitForm.js
  app/javascript/src/printLink/init.js
  app/views/account_details/emails/email_sent.html.haml
  app/views/payment_history/payment_history/payment_history.html.haml
  app/views/payments/payments/matrix/_pagination_button.html.haml
  app/views/vehicles_management/fleets/_view_charges_tab.html.haml
  package-lock.json
  package.json
  yarn.lock
Labels: bug

#1173 Fix accessibility tests authentication
  .drone2.yml
  ci-cd-resources/pa11y/.pa11yci.conf.js
Labels: bug

#1175 Fix accessibility tests authentication
  .drone2.yml
  ci-cd-resources/pa11y/.pa11yci.conf.js
Labels: bug
