Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2021-01, with the labels that each got.

#831 [CAZB-3820] Update prod URL pointer in drone file
  .drone2.yml
Labels: release

#836 [CAZB-3829] Change text on CSV upload pages
  app/views/vehicles_management/uploads/_description.html.haml
Labels: documentation

#844 Promote Accounts v1.6.4 to Production
  .drone2.yml
  app/views/vehicles_management/uploads/_description.html.haml
Labels: Accounts v1.6.4, dont merge yet, release

#820 [CAZB-3580] Update pagination on Date and Vehicle selection matrix
  Gemfile.lock
  app/api_wrappers/payments_api.rb
  app/controllers/payments/payments_controller.rb
  app/models/payments/chargeable_vehicles.rb
  app/models/payments/paginated_vehicles.rb
  app/models/payments/vehicle.rb
  app/models/user.rb
  app/models/vehicles_management/chargeable_fleet.rb
  app/models/vehicles_management/fleet.rb
  app/views/payments/payments/matrix.html.haml
  app/views/payments/payments/matrix/_heading.html.haml
  app/views/payments/payments/matrix/_next_week_tab.html.haml
  app/views/payments/payments/matrix/_pagination.html.haml
  app/views/payments/payments/matrix/_pagination_button.html.haml
  app/views/payments/payments/matrix/_past_week_tab.html.haml
  app/views/payments/payments/matrix/_table.html.haml
  features/payments.feature
  features/step_definitions/account_details/primary_user_steps.rb
  features/step_definitions/vehicles_management/fleets_steps.rb
  features/step_definitions/vehicles_management/uploads_step.rb
  features/support/mock_chargeable_vehicles.rb
  features/support/mock_debit.rb
  features/support/mock_fleet.rb
  package.json
  spec/api_wrappers/payments_api/chargeable_vehicle_spec.rb
  spec/api_wrappers/payments_api/chargeable_vehicles_spec.rb
  spec/fixtures/responses/chargeable_vehicle.json
  spec/fixtures/responses/chargeable_vehicles.json
  spec/fixtures/responses/payments/chargeable_vehicles.json
  spec/fixtures/responses/payments/chargeable_vehicles_with_unpaid_dates.json
  spec/helpers/payments_helpers_spec.rb
  spec/models/manage_vehicles/chargeable_fleet_spec.rb
  spec/models/manage_vehicles/chargeable_vehicle_spec.rb
  spec/models/manage_vehicles/fleet_spec.rb
  spec/models/manage_vehicles/paginated_vehicles_spec.rb
  spec/models/payments/chargeable_vehicles_spec.rb
  spec/models/payments/paginated_vehicles_spec.rb
  spec/rails_helper.rb
  spec/requests/payments/payments/clear_search_spec.rb
  spec/requests/payments/payments/in_progress_spec.rb
  spec/requests/payments/payments/local_authority_spec.rb
  spec/requests/payments/payments/matrix_spec.rb
  spec/requests/payments/payments/no_chargeable_vehicles_spec.rb
  spec/requests/payments/payments/review_spec.rb
  spec/requests/payments/payments/submit_search_spec.rb
  spec/requests/payments/payments/vrn_not_found_spec.rb
  spec/services/session_manipulation/add_vehicle_details_spec.rb
  spec/spec_helper.rb
  spec/support/chargeable_vehicles_factory.rb
  spec/support/payments/mocked_responses.rb
  yarn.lock
Labels: documentation, dont merge yet

#848 [CAZB-3756] Validate Non-alphabetic/numeric characters in search
  app/controllers/vehicles_management/fleets_controller.rb
  app/forms/search_vrn_form.rb
  app/forms/vehicles_management/search_vrn_form.rb
  spec/forms/search_vrn_form_spec.rb
Labels: bug

#838 [CAZB-3704] Add support for `partial search` in Payment Matrix
  Gemfile
  Gemfile.lock
  app/api_wrappers/fleets_api.rb
  app/api_wrappers/payments_api.rb
  app/controllers/concerns/caz_lock.rb
  app/controllers/payments/payments_controller.rb
  app/forms/vrn_form.rb
  app/models/concerns/log_action.rb
  app/models/payments/chargeable_vehicles.rb
  app/models/payments/paginated_vehicles.rb
  app/models/vehicles_management/fleet.rb
  app/views/payments/payments/matrix.html.haml
  app/views/payments/payments/matrix/_heading.html.haml
  config/application.rb
  config/environments/production.rb
  config/routes.rb
  features/support/mock_chargeable_vehicles.rb
  package.json
  spec/models/payments/paginated_vehicles_spec.rb
  spec/requests/payments/payments/in_progress_spec.rb
  spec/requests/payments/payments/local_authority_spec.rb
  spec/requests/payments/payments/matrix_spec.rb
  spec/requests/payments/payments/submit_search_spec.rb
  spec/spec_helper.rb
  spec/support/payments/mocked_responses.rb
  yarn.lock
Labels: documentation

#856 [CAZB-3756] Fix Non-alphabetic/numeric characters in search
  app/controllers/payments/payments_controller.rb
  app/controllers/vehicles_management/fleets_controller.rb
  app/javascript/packs/payment_matrix.js
  app/javascript/packs/redirect_to_timeout_notice.js
  app/javascript/src/payment_matrix/initPaginationButton.js
  app/services/session_manipulation/add_query_details.rb
  app/views/payments/payments/matrix/_pagination_button.html.haml
  spec/requests/payments/payments/submit_spec.rb
  spec/requests/vehicles_management/fleets/index_spec.rb
  spec/services/session_manipulation/add_query_details_spec.rb
  spec/support/shared_examples/non_continue_matrix_commit.rb
Labels: bug

#866 Promote Accounts v1.6.7 to Staging
  app/controllers/direct_debits/debits_controller.rb
  spec/requests/direct_debits/debits/create_spec.rb
  spec/requests/direct_debits/debits/index_spec.rb
  spec/requests/direct_debits/debits/new_spec.rb
Labels: Accounts v1.6.7, release

#869 [CAZB-3901] Update text
  app/views/static_pages/help.html.haml
Labels: documentation

#892 [CAZB-3751] Rewrite message to remove mention of fleets
  app/controllers/application_controller.rb
  app/views/organisations/organisations/verification_failed.html.haml
  features/organisations.feature
  spec/requests/organisations/email_verification_spec.rb
Labels: documentation

#895 [CAZB-3989] Change order of Select your preferred payment method
  app/views/payments/payments/select_payment_method.html.haml
Labels: documentation

#900 [CAZB-3747] Remove the second bullet text on vehicles not found page
  app/views/vehicles_management/fleets/vrn_not_found.html.haml
Labels: documentation

#901 [CAZB-3634] Rename tab heading on matrix page
  app/views/payments/payments/matrix/_past_week_tab.html.haml
  app/views/payments/payments/matrix/_tabs.html.haml
  features/payments.feature
Labels: documentation

#911 [CAZB-3858] Terms and conditions
  app/views/static_pages/terms_and_conditions.html.haml
Labels: bug
