Repository InformedSolutions/JAQU-CAZ-Fleets-UI, pull requests merged in 2021-02, with the labels that each got.

#908 Promote Accounts v1.7.0 to Production
  .drone.yml
  app/api_wrappers/fleets_api.rb
  app/controllers/vehicles_management/fleets_controller.rb
  app/forms/search_vrn_form.rb
  app/forms/vehicles_management/search_vrn_form.rb
  app/views/vehicles_management/fleets/index.html.haml
  spec/forms/search_vrn_form_spec.rb
  spec/requests/vehicles_management/fleets/index_spec.rb
Labels: Accounts v1.7.0, release

#912 Promote Accounts v1.7.5 to Pre-Prod
  app/controllers/application_controller.rb
  app/views/dashboard/_d_day_notice.html.haml
  app/views/dashboard/_direct_debit.html.haml
  app/views/dashboard/_make_payment.html.haml
  app/views/direct_debits/debits/index.html.haml
  app/views/direct_debits/debits/new.html.haml
  app/views/organisations/organisations/verification_failed.html.haml
  app/views/payments/payments/select_payment_method.html.haml
  app/views/static_pages/help.html.haml
  app/views/static_pages/privacy_notice.html.haml
  app/views/static_pages/terms_and_conditions.html.haml
  app/views/users_management/create_users/add_permissions.html.haml
  app/views/users_management/edit_users/edit.html.haml
  app/views/vehicles_management/fleets/index.html.haml
  features/dashboard/owner_dashboard.feature
  features/dashboard/user_dashboard.feature
  features/debits.feature
  features/organisations.feature
  features/payments.feature
  spec/requests/organisations/email_verification_spec.rb
Labels: Accounts v1.7.5, release

#913 Promote Accounts v1.7.5 to Production
  app/controllers/application_controller.rb
  app/views/dashboard/_d_day_notice.html.haml
  app/views/dashboard/_direct_debit.html.haml
  app/views/dashboard/_make_payment.html.haml
  app/views/direct_debits/debits/index.html.haml
  app/views/direct_debits/debits/new.html.haml
  app/views/organisations/organisations/verification_failed.html.haml
  app/views/payments/payments/select_payment_method.html.haml
  app/views/static_pages/help.html.haml
  app/views/static_pages/privacy_notice.html.haml
  app/views/static_pages/terms_and_conditions.html.haml
  app/views/users_management/create_users/add_permissions.html.haml
  app/views/users_management/edit_users/edit.html.haml
  app/views/vehicles_management/fleets/index.html.haml
  features/dashboard/owner_dashboard.feature
  features/dashboard/user_dashboard.feature
  features/debits.feature
  features/organisations.feature
  features/payments.feature
  spec/requests/organisations/email_verification_spec.rb
Labels: Accounts v1.7.5, dont merge yet, release

#916 [CAZB-4063] Migrate pipeline to Terraform v0.12.23
  .drone.yml
  .drone2.yml
Labels: bug

#917 Promote release v1.7.6 to pre-production
  .drone.yml
  .drone2.yml
Labels: Accounts v1.7.6, release

#918 Promote Accounts v1.7.6 to Production
  .drone.yml
  .drone2.yml
Labels: Accounts v1.7.6, release

#930 [CAZB-4116] Make the results per page option dynamic
  .rubocop.yml
  .ruby-version
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/forms/base_form.rb
  app/forms/organisations/company_name_form.rb
  app/models/vehicles_management/paginated_fleet.rb
  app/views/vehicles_management/fleets/_pagination.html.haml
  app/views/vehicles_management/fleets/index.html.haml
  features/support/mock_fleet.rb
  features/vehicles_management/fleets.feature
  lib/custom_logger.rb
  package.json
  spec/models/manage_vehicles/paginated_vehicles_spec.rb
  spec/rails_helper.rb
  spec/support/fleet_factory.rb
  yarn.lock
Labels: documentation

#932 [CAZB-4116] Do not render empty div block if vehicles less than 10
  app/controllers/vehicles_management/fleets_controller.rb
  app/javascript/src/printLink/styles.scss
  app/javascript/styles/application.scss
  app/views/vehicles_management/fleets/_pagination.html.haml
  app/views/vehicles_management/fleets/index.html.haml
Labels: bug

#933 [CAZB-4174] Marks an account name as trusted safe for page titles
  app/views/dashboard/_company_payment_history.html.haml
  app/views/dashboard/index.html.haml
  app/views/payment_history/payment_history/company_payment_history.html.haml
  app/views/users_management/create_users/new.html.haml
  app/views/users_management/users/index.html.haml
  app/views/vehicles_management/fleets/choose_method.html.haml
  app/views/vehicles_management/fleets/remove.html.haml
  app/views/vehicles_management/uploads/index.html.haml
  features/dashboard/owner_dashboard.feature
  features/dashboard/user_dashboard.feature
  features/payment_history.feature
  features/payments.feature
  features/sign_in.feature
  features/step_definitions/account_details/emails_steps.rb
  features/support/mock_users.rb
  features/support/sign_in_helper.rb
  features/users_management/manage_users.feature
  features/vehicles_management/uploads.feature
Labels: bug

#940 [CAZB-4174] Do not escape tags an account name for page titles
  app/views/dashboard/index.html.haml
  app/views/users_management/create_users/new.html.haml
  app/views/users_management/users/index.html.haml
  app/views/vehicles_management/fleets/choose_method.html.haml
  app/views/vehicles_management/fleets/remove.html.haml
  app/views/vehicles_management/uploads/index.html.haml
Labels: bug
